from typing import Any


class RefMethods:
    def __init__(self, ref: Any) -> None: ...
    def info(self, limit: int = 10) -> None: ...
    @property
    def expr(self) -> Any: ...
    def get_expr_dependencies(self) -> list[Any]: ...
    def find_dependant_targets(self) -> Any: ...


class BaseRef:
    ...


class MutableRef(BaseRef):
    @property
    def xdeps(self) -> RefMethods: ...


class ItemRef(MutableRef):
    ...
