# This is a `.pyi` type stub file for the compiled `xdeps.refs` module.
# Stub files describe the public API (types, attributes, method signatures)
# for static tools (IDEs, Jedi, type checkers), without affecting runtime code.
# We add it here because `xdeps.refs` is loaded from a compiled extension
# (`refs.cpython-*.so`), and completers could not infer that
# `MutableRef.xdeps` returns `RefMethods` for chained autocompletion.
from typing import Any


class RefMethods:
    def __init__(self, ref: Any) -> None: ...
    def __repr__(self) -> str: ...
    def info(self, limit: int = 10) -> None: ...
    @property
    def expr(self) -> Any: ...
    @property
    def value(self) -> Any: ...
    @property
    def manager(self) -> Any: ...
    @property
    def expr_dependencies(self) -> list: ...
    @property
    def controlled_targets(self) -> list: ...

class BaseRef:
    ...


class MutableRef(BaseRef):
    @property
    def xdeps(self) -> RefMethods: ...


class ItemRef(MutableRef):
    ...
