name: Publish Xdeps to PyPI

on:
  push:
    tags:
      - v*

jobs:
  build-wheels:
    name: Build wheels for ${{ matrix.pyver }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        pyver: [cp38, cp39, cp310, cp311, cp312]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.pyver }}-*
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"

      - uses: actions/upload-artifact@v4
        with:
          name: dist-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz

  publish-to-pypi:
    name: Publish Xdeps to PyPI
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    environment:
      name: pypi
      url: https://pypi.org/p/xdeps
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        path: dist
        merge-multiple: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
